from django.db import models

from apps.product.models import Product
from apps.user.models import BaseModel, User


class Bonus(models.Model):
    product = models.ForeignKey(Product, models.SET_NULL, 'bonuses', blank=True, null=True)
    summa = models.IntegerField(default=1, verbose_name="Amount of bonus", blank=True, null=True)
    prefix = models.CharField(
        max_length=20,
        verbose_name="First bonus code",
        help_text="Enter the first printed code exactly as-is, e.g. LPM2A0000. "
                   "The remaining codes are generated by incrementing its trailing digits.",
        blank=True,
        default="",
    )
    quantity = models.PositiveIntegerField(default=9999, verbose_name="Amount of code")
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        verbose_name = 'Bonus'
        verbose_name_plural = 'Bonuses'

    def __str__(self):
        return f"Bonus #{self.pk} - {self.product}"


class BonusCode(BaseModel):
    bonus = models.ForeignKey(Bonus, models.SET_NULL, related_name='codes', verbose_name="Bonus", null=True,)
    code = models.CharField(max_length=100, unique=True, verbose_name="Code")
    is_used = models.BooleanField(default=False, verbose_name="Used")

    class Meta:
        verbose_name = 'Bonus Code'
        verbose_name_plural = 'Bonus Codes'

    def __str__(self):
        return self.code if self.code else f"BonusCode #{self.pk}"


class BonusClaimStatus(models.TextChoices):
    PENDING = "pending", "Pending"
    APPROVED = "approved", "Approved"
    REJECTED = "rejected", "Rejected"


class UserSumma(BaseModel):
    user = models.ForeignKey(User, models.CASCADE, 'points')
    bonus = models.ForeignKey(Bonus, models.SET_NULL, 'redemptions', null=True, blank=True,
                              verbose_name="Бонус")
    code = models.OneToOneField(BonusCode, models.CASCADE, related_name='redemption', verbose_name="Код")
    store = models.ForeignKey("shared.Store", on_delete=models.SET_NULL, null=True, related_name="bonus_claims")
    # Snapshot of Bonus.product at redemption time — Bonus.product may be reassigned later,
    # and challenge progress must count what the user actually redeemed at the time.
    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL, null=True, blank=True,
        related_name="bonus_redemptions", verbose_name="Mahsulot",
    )
    # The amount granted at redemption time — Bonus.summa may be edited later, and the
    # expiry job must give back exactly what was given.
    summa = models.IntegerField(default=0, verbose_name="Сумма")
    status = models.CharField(max_length=20, choices=BonusClaimStatus.choices, default=BonusClaimStatus.PENDING)
    rejection_reason = models.CharField(max_length=255, blank=True)
    reviewed_at = models.DateTimeField(null=True, blank=True)
    reviewed_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name="reviewed_claims")
    is_expired = models.BooleanField(default=False, verbose_name="Истёк")

    def __str__(self):
        return f"{self.user.username} - {self.code.code}"


class UserSummaImage(models.Model):
    user_summa = models.ForeignKey(UserSumma, models.CASCADE, related_name='images',
                                   verbose_name="Redemption")
    image = models.ImageField(upload_to='bonus_images/', verbose_name="Фото")

    class Meta:
        verbose_name = 'Redemption Image'
        verbose_name_plural = 'Redemption Images'

    def __str__(self):
        return f"Image for {self.user_summa}"


class Challenge(BaseModel):
    title = models.CharField(max_length=255)
    description = models.TextField()
    product = models.ForeignKey(
        Product, on_delete=models.PROTECT,
        related_name="challenges", verbose_name="Mahsulot",
        help_text="Only approved claims for this product count toward the challenge target, "
                   "e.g. \"8/10 ACM nasosi o'rnatilgan bo'lsa\".",
    )
    target_count = models.PositiveIntegerField()
    reward_amount = models.BigIntegerField()
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class UserChallengeProgress(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="challenge_progress")
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE, related_name="user_progress")
    current_count = models.PositiveIntegerField(default=0)
    is_completed = models.BooleanField(default=False)
    completed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        unique_together = ("user", "challenge")

    def __str__(self):
        return f"{self.user.username} - {self.challenge.title}: {self.current_count}/{self.challenge.target_count}"
