name: Deploy

on:
  push:
    branches: [test]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy over SSH step
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          eval "$(ssh-agent -s)"
          echo "$SSH_PRIVATE_KEY" | ssh-add -

          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            set -e
            cd /var/www/leo
            git pull origin test
            export UV_PROJECT_ENVIRONMENT=/var/www/leo/venv
            export UV_PYTHON_DOWNLOADS=never
            uv sync --locked --no-dev
            uv run manage.py makemigrations
            uv run manage.py migrate --noinput
            uv run manage.py collectstatic --noinput
            sudo systemctl restart leo_backend.service
          '